version: 1
projectName: mcp-client-chatbot
services:
  - type: application
    name: mcp-chatbot
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NO_HTTPS=1
    envFiles:
      - .env
    dependsOn:
      - postgres
    healthCheck:
      path: /api/health
      port: 3000

  - type: postgresql
    name: postgres
    version: "17"
    databases:
      - name: mcp_chatbot
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mcp_chatbot
    restart: unless-stopped
