version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mcp-chatbot
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NO_HTTPS=1
      - POSTGRES_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/mcp_chatbot
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:17
    container_name: mcp-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mcp_chatbot}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mcp-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-mcp_chatbot}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge

volumes:
  postgres_data:
